### ISSUE TITLE
webfx create application does not validate package syntax

### ISSUE THREAD

**Issue by armin-reichert** [webfx-project/webfx-cli#7]
By mistyping, I entered `webfx create application --prefix hello-webfx de,amr.WebFXApp --helloWorld` (a comma instead of a dot). I would expect that this input is rejected instead of creating everything (files, module info) with the invalid syntax.

**Comment by salmonb** [comment]
Thanks for spotting this, this is now fixed. You can get the latest version with `webfx bump cli`. Let me know if it works so we can close this issue.

**Comment by armin-reichert** [comment]
Hm, updating seems not to work. It says:
```
C:\Users\Armin\git\pacman-javafx\web-fx>webfx bump cli
C:\Users\Armin\git\webfx-cli> git pull -r
A new version is available!
Old version: 0.1.0-SNAPSHOT ~ 2023-04-02 10:24 GMT
C:\Users\Armin\git\webfx-cli> mvn package
New version: 0.1.0-SNAPSHOT ~ 2023-04-02 10:24 GMT
```

And after this "update" the problem still exists.
